name: Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Build docs
        run: crystal docs --project-name Representer --project-version 1.2.0
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@94f3c658273cf92fb48ef99e5fbc02bd2dc642b2
        with:
          branch: gh-pages
          folder: docs # The folder the action should deploy.
          clean: true
