name: Docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    container:
      image: crystallang/crystal
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Build docs
        run: crystal docs --project-name Representer --project-version 1.2.0
      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e
        with:
          branch: gh-pages
          folder: docs # The folder the action should deploy.
          clean: true
